# Use a Node.js image as a base
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire content of the public directory to the working directory
COPY public/ ./public/

# Copy the entire content of the src directory to the working directory
COPY src/ ./src/

# Build the React app for production
RUN npm run build

# Expose the port that the app runs on
EXPOSE 3000

# Define the command to run the app when the container starts
CMD ["npm", "start"]
